### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by lssimoes** [kaslusimoes/SocialSystems.jl#1]
Things to do/implement until the end of the semester (until my semester report):
- [ ] Add more Order Parameters to measure a Society
- [ ] Add more MCMC Methods
- [ ] Add more ways to discuss issues on a Society
- [ ] Implement Media Interference

Interesting things to do before it's too late:
- [ ] Document and reorganize messy code
- [ ] Add Julia Tests
- [ ] Add Code Coverage
